config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # Home page route
  root "clubs#index"

  # About page route
  get '/about', to: "about#index"

  resources :about

  # User authentication
  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }

  # Clubs and Ratings
  resources :clubs do
    resources :ratings
  end

  resources :ratings

  # My Ratings
  get "/my_ratings", to: "clubs#my_ratings"

  resources :my_ratings

  # Categories
  resources :categories

  # We are not using the below anymore
  # Assignments route
  get "/assignments", to: "assignments#index"

  resources :assignments

  # Add A3 work below
  get "/assignments/a3Lawrence", to: "assignments#a3Lawrence"
  get "/assignments/a3ThanhQuan", to: "assignments#a3ThanhQuan"
  get "/assignments/a3Minkyu", to: "assignments#a3Minkyu"
  get "/assignments/a3Max", to: "assignments#a3Max"
  get "/assignments/a3Cynthia", to: "assignments#a3Cynthia"

  # Add A4 work below
  get "/assignments/a4Lawrence", to: "assignments#a4Lawrence"
  get "/assignments/a4ThanhQuan", to: "assignments#a4ThanhQuan"
  get "/assignments/a4Max", to: "assignments#a4Max"
  get "/assignments/a4Minkyu", to: "assignments#a4Minkyu"
  get "/assignments/a4Cynthia", to: "assignments#a4Cynthia"

  namespace :assignments do
    namespace :a4_thanh_quan do
      resources :tests
    end
  end

end

app/models/club.rb
class Club < ApplicationRecord
  # Validate that the club name and overall rating are not empty.
  # Validate that the club name is not duplicated, or less than 5 characters.
  validates :name, presence: true, uniqueness: true, length: { minimum: 5 }, obscenity: true

  # Validate that the overall rating is a number between 1 and 5

  # NOTE: Removed since users should not be able to edit this default value.
  # validates_inclusion_of :overall_rating, :in => 1..5

  belongs_to :category
  has_many :ratings, dependent: :destroy

  def self.search(search)
    if search
      club = Club.where('lower(name) LIKE ?', '%' + search.downcase + '%').all
    else
      Club.all
    end
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: %i[ show edit update destroy ]

  # GET /clubs or /clubs.json
  def index
    @categories = Category.all
    @clubs = Club.search(params[:search])
  end

  def my_ratings
    @clubs = Club.all
    @ratings = Rating.all
  end

  # GET /clubs/1 or /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs or /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: "Club was successfully created." }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1 or /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: "Club was successfully updated." }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1 or /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: "Club was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def club_params
      params.require(:club).permit(:name, :overall_rating, :category_id, :search)
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_form.html.erb
<%= form_with(model: club) do |form| %>
  <% if club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
        <% club.errors.each do |error| %>
          <p><%= error.full_message %></p>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="create-club-box">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :category %>
      <div class="club-form-category-select">
        <%= form.collection_select(:category_id, Category.all, :id, :name) %>
      </div>
    </div>

    <div class="actions">
      <br>
      <%= form.submit %>
    </div>
  </div>

  <div class="club-copyrighted">
    <p>Copyrighted 2021</p>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing Club</h1>

<!--<%= render 'form', club: @club %>-->
  <div id="prompt3">
    <p>You do not have permission to edit clubs. Only administrators can.</p>
  </div>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<!--This notice is for showing "Signed out successfully" and 
"Signed in successfully" in rate this club page-->
<p id="notice"><%= notice %></p>

<h1 class="home-page-h1">Rate My Clubs</h1>

<div class="home-page-row">
  <div class="home-category-list">
      <div class="home-category-background">
        <h2 class="home-category-heading">Categories</h2>
        <%= render :partial => "categories/list", locals: {categories: @categories}%>
      </div>
  </div>
  <div class="home-main-container">
    <% if @clubs.first.nil? == true %>
      <div class="home-no-clubs">
        <div class="home-no-clubs-text">No clubs available.</div>
      </div>
    <% else %>
      <div class="home-page-column">
        <div class="home-content-container">
          <% @clubs.each do |club| %>
            <div class="home-club-container clubs-tr home-row" data-link= "<%= club_path(club.id) %>">
              <div class ="home-ratings-column">
                <div class="home-overall-rating-container">
                  <div class="home-overall-rating">
                    <% if club.overall_rating == -1 %>
                      <div>N/A</div>
                    <% else %>
                      <div><%= club.overall_rating %></div>
                    <% end %>
                  </div>
                </div>
                <div class="home-number-rating">
                  <% if club.ratings.count == 1 %>
                    <%= club.ratings.count %> rating
                  <% else %>
                    <%= club.ratings.count %> ratings
                  <% end %>
                </div>
              </div>
              <div class="home-club-info-column">
                <div class="home-club-name"><%= club.name %></div>
                <div class="home-category-name"><%= Category.find(club.category_id).name %></div>
              </div>
              <div class="home-other-ratings-column">
                <div class="home-other-ratings-metric-row">
                  <p class="home-rating">
                    <% if club.career_oriented_rating == -1 %>
                      N/A
                    <% else %>
                      <%= club.career_oriented_rating %>
                    <% end %>
                  </p>
                  <p class="home-rating-metric">Career-Oriented</p>
                </div>
                <div class="home-other-ratings-metric-row">
                  <p class="home-rating">
                    <% if club.enjoyment_rating == -1 %>
                      N/A
                    <% else %>
                      <%= club.enjoyment_rating %>
                    <% end %>
                  </p>
                  <p class="home-rating-metric">Enjoyment</p>
                </div>
                <div class="home-other-ratings-metric-row">
                  <p class="home-rating">
                    <% if club.community_rating == -1 %>
                      N/A
                    <% else %>
                      <%= club.community_rating %>
                    <% end %>
                  </p>
                  <p class="home-rating-metric">Community</p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
    <% end %>
  </div>
</div>
  
</div>



<br>

<!-- Required JavaScript file import "home.js" located in app/javascript/packs -->
<%= javascript_pack_tag 'home' %>

<!--
Only logged in users can create clubs. Leaving this here for reference.
<%= link_to 'New Club', new_club_path %>
-->

app/views/clubs/my_ratings.html.erb
<div class="my-ratings-page">
  <h1 class="my-ratings-h1">My Ratings</h1>

  <% if user_signed_in? %>

    <!-- Boolean to check if user has rating, else display message -->
    <% hasRating = false %>

    <!-- For each club, display club name and overall rating -->
    <!-- Then display user's general rating and description -->
    <% @clubs.each do |club| %>

      <% if club.ratings.exists?(user_id: current_user.id) %>

        <!-- Club overall_rating and Club name -->
        <div class="my-ratings-club-name-container my-ratings-row">
          <div class="my-overall-rating-box">
            <%= club.overall_rating %>
          </div>
          <span class="my-ratings-club-name">  <%= club.name %> </span>
        </div>

        <br />

        <!-- User rating and User description -->
        <% rating = club.ratings.find_by(user_id: current_user.id) %>

        <div class="my-ratings-container">

          <div class="rating-rectangle">
        
            <div class="overall-rating-box">
              <span class= "overall-rating-text"> <%= rating.general_rating %> </span>
            </div>
        
            <div class="rating-metric-box4">
              <span class= "metric-rating-text"> <%= rating.career_oriented_rating %> </span>
            </div>
        
            <div class="rating-metric-box5">
              <span class= "metric-rating-text"> <%= rating.enjoyment_rating %> </span>
            </div>
        
            <div class="rating-metric-box6">
              <span class= "metric-rating-text"> <%= rating.community_rating %> </span>
            </div>
        
            <div class="rating-metric-name1">
            Career-Oriented
            </div>
            
            <div class="rating-metric-name2">
            Enjoyment
            </div>
        
            <div class="rating-metric-name3">
            Community
            </div>
            
            <div class="rating-date">
              <%= rating.created_at.strftime("%B %d, %Y") %>
            </div>
        
            <div class="delete-rating-button">
            <% if user_signed_in? and rating.user_id == current_user.id %>
            <%= link_to 'Destroy Rating', [rating.club, rating],
                        method: :delete,
                        data: { confirm: "Are you sure?" } %>
            <% end %>
            </div>
        
            <div class="description-box">
              <%= rating.description %>
            </div>
          
          </div>
        </div>
      
      
        <br />

        <br />

        <% if hasRating == false %>
          <% hasRating = true %>
        <% end %>
      <% end %>
    <% end %>

    <!-- If user has no ratings, provide no-ratings-message -->
    <% if hasRating == false %>
      <p class="no-ratings-message">You don't have any ratings! Add a rating to a club page by clicking on a club on the home page.</p>
    <% end %>

  <% else %>
    <p class="my-ratings-not-logged-in-message">You need to be logged in to view your ratings.</p>
  <% end %>

</div>

app/views/clubs/new.html.erb
<h1 class="category-club-header">Create New Club</h1>

<% if user_signed_in? %>
  <%= render 'form', club: @club %>
<% else %>
  <p>You must be logged in to create clubs!</p>
<% end %>

<!--Remove Back button from create new club page-->
<!--<%= link_to 'Back', categories_path %>-->

app/views/clubs/show.html.erb
<!--This notice is for showing error message in rate this club-->
<p id="notice"><%= notice %></p>

<div class="club-overall-info-container">

  <div class="overall-rating-box">
    <div class="overall-rating">
    <%= 
    if @club.overall_rating == -1 
      "N/A"
    else
      @club.overall_rating
    end
    %>
    </div> 
  </div>

  <div class="rating-metric-box1"> 
    <%= 
      if @club.career_oriented_rating == -1 
        "N/A"
      else
        @club.career_oriented_rating
      end
    %>
  </div>

  <div class="rating-metric-box2"> 
    <%= 
    if @club.enjoyment_rating == -1 
      "N/A"
    else
      @club.enjoyment_rating
    end
    %>
  </div>

  <div class="rating-metric-box3"> 
    <%= 
    if @club.community_rating == -1 
      "N/A"
    else
      @club.community_rating
    end
    %>
  </div>
  
  <div class= "overall-rating-names">
    <strong><%= @club.name %></strong>
    <p> <%= Category.find(@club.category_id).name %> </p>
    <br><br>Career-Oriented
    <br><br><br><br>Enjoyment
    <br><br><br><br>Community
  </div>
</div>

<% if user_signed_in? %>
  <% if !@club.ratings.exists?(user_id: current_user.id) %>
    <!-- Ratings -->
    <%= render @club.ratings %>
    <%= render 'ratings/form' %>
  <% else %>
    <div id="prompt1">
      <p>Looking to create a rating? You already created one! Users can only have one rating per club page.</p>
    </div>
    <br />
    <!-- Ratings -->
    <%= render @club.ratings %>  
    <% end %>
<% else %>
  <div id="prompt2">
    <p>Sign in to create ratings.</p>
  </div>
  <br />
  <!-- Ratings -->
  <%= render @club.ratings %>  
<% end %>

<!-- Do not allow users to edit clubs -->
<!--<%= link_to 'Edit', edit_club_path(@club) %> |-->