config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # Home page route
  root "clubs#index"

  # About page route
  get '/about', to: "about#index"

  resources :about

  # User authentication
  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }

  # Clubs and Ratings
  resources :clubs do
    resources :ratings
  end

  resources :ratings

  # My Ratings
  get "/my_ratings", to: "clubs#my_ratings"

  resources :my_ratings

  # Categories
  resources :categories

  # We are not using the below anymore
  # Assignments route
  get "/assignments", to: "assignments#index"

  resources :assignments

  # Add A3 work below
  get "/assignments/a3Lawrence", to: "assignments#a3Lawrence"
  get "/assignments/a3ThanhQuan", to: "assignments#a3ThanhQuan"
  get "/assignments/a3Minkyu", to: "assignments#a3Minkyu"
  get "/assignments/a3Max", to: "assignments#a3Max"
  get "/assignments/a3Cynthia", to: "assignments#a3Cynthia"

  # Add A4 work below
  get "/assignments/a4Lawrence", to: "assignments#a4Lawrence"
  get "/assignments/a4ThanhQuan", to: "assignments#a4ThanhQuan"
  get "/assignments/a4Max", to: "assignments#a4Max"
  get "/assignments/a4Minkyu", to: "assignments#a4Minkyu"
  get "/assignments/a4Cynthia", to: "assignments#a4Cynthia"

  namespace :assignments do
    namespace :a4_thanh_quan do
      resources :tests
    end
  end

end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :club

  # Validate that the ratings, description, and school year are not empty.
  validates :general_rating, :career_oriented_rating, :enjoyment_rating, :community_rating, 
            :description, presence: true

  # Validate that the description are maximum 500 characters and not duplicate.
  validates :description, length: { maximum: 500 }, uniqueness: true, obscenity: true

  # Validate ratings is a number between 1 and 5
  validates_inclusion_of :general_rating, :career_oriented_rating, :enjoyment_rating, :community_rating, 
                          :in => 1..5

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: %i[ show edit update destroy ]
  after_action :update_ratings_to_clubs, only: [:create, :destroy]

  # GET /ratings or /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1 or /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings or /ratings.json
  def create
    @club = Club.find(params[:club_id])
    @rating = @club.ratings.create(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to club_path(@club), notice: "Rating was successfully created." }
        format.json { render :show, status: :created, location: @rating }
      else
        #format.html { render :new, status: :unprocessable_entity }
        format.html { redirect_to club_path(@club), notice: @rating.errors.full_messages.to_sentence }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1 or /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: "Rating was successfully updated." }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1 or /ratings/1.json
  def destroy
    @club = Club.find(params[:club_id])
    @rating = @club.ratings.find(params[:id])

    @rating.destroy
    respond_to do |format|
      format.html { redirect_to club_path(@club), notice: "Rating was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Callback for updating club's overall rating
    def update_ratings_to_clubs
      if @club.ratings.count == 0
        @club.update(overall_rating: -1)
        @club.update(career_oriented_rating: -1)
        @club.update(enjoyment_rating: -1)
        @club.update(community_rating: -1)
      else
        @club.update(overall_rating: @club.ratings.average(:general_rating).round(1))
        @club.update(career_oriented_rating: @club.ratings.average(:career_oriented_rating).round(1))
        @club.update(enjoyment_rating: @club.ratings.average(:enjoyment_rating).round(1))
        @club.update(community_rating: @club.ratings.average(:community_rating).round(1))
      end
    end

    # Only allow a list of trusted parameters through.
    def rating_params
      params.require(:rating).permit(:general_rating, :description, 
        :career_oriented_rating, :enjoyment_rating, :community_rating, :club_id, :user_id)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_with model: [ @club, @club.ratings.build ] do |form| %>
  <% if @club.ratings.build.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.ratings.build.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
        <% @club.ratings.build.errors.each do |error| %>
          <h3><%= error.full_message %></h3>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="club-page">
  <div class="new-rating-container">
    <div class="new-rating-rectangle">
      <strong>Rate this Club</Strong>

      <div class="general-rating-field">
        <%= form.label :general_rating %>


          <div class="rate">

            <input type="radio" id="general rating star5" name="rating[general_rating]" value="5" />
            <label for="general rating star5"> 5 stars</label>

            <input type="radio" id="general rating star4" name="rating[general_rating]" value="4" />
            <label for="general rating star4"> 4 stars</label>

            <input type="radio" id="general rating star3" name="rating[general_rating]" value="3" />
            <label for="general rating star3"> 3 stars</label>

            <input type="radio" id="general rating star2" name="rating[general_rating]" value="2" />
            <label for="general rating star2"> 2 stars</label>

            <input type="radio" id="general rating star1" name="rating[general_rating]" value="1" />
            <label for="general rating star1"> 1 star</label>
            
          </div>

      </div>

      <div class="rating-description">
        <%= form.label :description %> <br>
        <%= form.text_area :description, class: 'rating-description-border' %>

      </div>
    
      <div class="rating-field">


        <div class="field">
          <%= form.label :career_oriented_rating %>
          <p>
            <div class="rate">

              <input type="radio" id="career star5" name="rating[career_oriented_rating]" value="5" />
              <label for="career star5"> 5 stars</label>

              <input type="radio" id="career star4" name="rating[career_oriented_rating]" value="4" />
              <label for="career star4"> 4 stars</label>

              <input type="radio" id="career star3" name="rating[career_oriented_rating]" value="3" />
              <label for="career star3"> 3 stars</label>

              <input type="radio" id="career star2" name="rating[career_oriented_rating]" value="2" />
              <label for="career star2"> 2 stars</label>

              <input type="radio" id="career star1" name="rating[career_oriented_rating]" value="1" />
              <label for="career star1"> 1 star</label>
              
            </div>
          </p>
        </div>

        <div class="field">
          <%= form.label :enjoyment_rating %>
          <p>
            <div class="rate">

              <input type="radio" id="enjoyment star5" name="rating[enjoyment_rating]" value="5" />
              <label for="enjoyment star5"> 5 stars</label>

              <input type="radio" id="enjoyment star4" name="rating[enjoyment_rating]" value="4" />
              <label for="enjoyment star4"> 4 stars</label>

              <input type="radio" id="enjoyment star3" name="rating[enjoyment_rating]" value="3" />
              <label for="enjoyment star3"> 3 stars</label>

              <input type="radio" id="enjoyment star2" name="rating[enjoyment_rating]" value="2" />
              <label for="enjoyment star2"> 2 stars</label>

              <input type="radio" id="enjoyment star1" name="rating[enjoyment_rating]" value="1" />
              <label for="enjoyment star1"> 1 star</label>
              
            </div>
          </p>
        </div>

        <div class="field">
          <%= form.label :community_rating %>
          <p>
            <div class="rate">

              <input type="radio" id="community star5" name="rating[community_rating]" value="5" />
              <label for="community star5"> 5 stars</label>

              <input type="radio" id="community star4" name="rating[community_rating]" value="4" />
              <label for="community star4"> 4 stars</label>

              <input type="radio" id="community star3" name="rating[community_rating]" value="3" />
              <label for="community star3"> 3 stars</label>

              <input type="radio" id="community star2" name="rating[community_rating]" value="2" />
              <label for="community star2"> 2 stars</label>

              <input type="radio" id="community star1" name="rating[community_rating]" value="1" />
              <label for="community star1"> 1 star</label>
              
            </div>
          </p>
        </div>
      </div>

      <%= form.hidden_field :user_id, value: current_user.id %>

      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </div>
</div>


<% end %>

app/views/ratings/_rating.html.erb
<div class="club-page">
  <div class="ratings-container">

    <div class="rating-rectangle">

      <div class="overall-rating-box">
        <span class= "overall-rating-text"> <%= rating.general_rating %> </span>
      </div>

      <div class="rating-metric-box4">
        <span class= "metric-rating-text"> <%= rating.career_oriented_rating %> </span>
      </div>

      <div class="rating-metric-box5">
        <span class= "metric-rating-text"> <%= rating.enjoyment_rating %> </span>
      </div>

      <div class="rating-metric-box6">
        <span class= "metric-rating-text"> <%= rating.community_rating %> </span>
      </div>

      <div class="rating-metric-name1">
      Career-Oriented
      </div>
      
      <div class="rating-metric-name2">
      Enjoyment
      </div>

      <div class="rating-metric-name3">
      Community
      </div>
      
      <div class="rating-date">
        <%= rating.created_at.strftime("%B %d, %Y") %>
      </div>

      <div class="delete-rating-button">
      <% if user_signed_in? and rating.user_id == current_user.id %>
      <%= link_to 'Destroy Rating', [rating.club, rating],
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
      <% end %>
      </div>

      <div class="description-box">
        <%= rating.description %>
      </div>
    
    </div>
  </div>
</div>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ratings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form', rating: @rating %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>