config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # Home page route
  root "clubs#index"

  # About page route
  get '/about', to: "about#index"

  resources :about

  # User authentication
  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }

  # Clubs and Ratings
  resources :clubs do
    resources :ratings
  end

  resources :ratings

  # My Ratings
  get "/my_ratings", to: "clubs#my_ratings"

  resources :my_ratings

  # Categories
  resources :categories

  # We are not using the below anymore
  # Assignments route
  get "/assignments", to: "assignments#index"

  resources :assignments

  # Add A3 work below
  get "/assignments/a3Lawrence", to: "assignments#a3Lawrence"
  get "/assignments/a3ThanhQuan", to: "assignments#a3ThanhQuan"
  get "/assignments/a3Minkyu", to: "assignments#a3Minkyu"
  get "/assignments/a3Max", to: "assignments#a3Max"
  get "/assignments/a3Cynthia", to: "assignments#a3Cynthia"

  # Add A4 work below
  get "/assignments/a4Lawrence", to: "assignments#a4Lawrence"
  get "/assignments/a4ThanhQuan", to: "assignments#a4ThanhQuan"
  get "/assignments/a4Max", to: "assignments#a4Max"
  get "/assignments/a4Minkyu", to: "assignments#a4Minkyu"
  get "/assignments/a4Cynthia", to: "assignments#a4Cynthia"

  namespace :assignments do
    namespace :a4_thanh_quan do
      resources :tests
    end
  end

end

app/views/header/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css" rel="stylesheet">
  <%= javascript_pack_tag 'home' %>
</head>
  <body>
<nav class="header-nav">
  <div class="menu-icon"><span class="fa fa-bars"></span></div>
  <div class="logo"><%= link_to image_tag("favicon.ico"), root_path, method: :get %></div>
  <% if user_signed_in? %>  
    <div class="nav-items">
      <li><%= link_to 'About', about_path , method: :get%></li>
      <li><%= link_to 'Club Categories', categories_path, method: :get %></li>
      <li class="mobile-menu"><%= link_to 'Create Club', new_club_path, method: :get %></li>
      <li class="mobile-menu"><%= link_to 'Create Category', new_category_path, method: :get %></li>
      <li class="mobile-menu"><%= link_to 'My Ratings', my_ratings_path, method: :get %></li>
      <li class="mobile-menu"><%= link_to "Settings", edit_user_registration_path, method: :get %></li>
      <li class="mobile-menu"><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
    </div>
    <div class="search-icon"><span class="fa fa-search"></span></div>
    <div class="cancel-icon"><span class="fa fa-times"></span></div>
    <%= form_tag(clubs_path, method: :get) do %>
      <%= text_field_tag(:search, params[:search], placeholder: "Search for Club", class: "search-data") %>
      <button type="submit" class="fa fa-search" style="color: black"></button>
    <% end %> 
    <div class="dropdown dropdown-menu">
      <button class="dropbtn" onclick="myFunction()">
        <i class="fa fa-user"></i>&nbsp;
        <%= current_user.username %>
        <i class="fa fa-caret-down"></i>
      </button>
      <div class="dropdown-content" id="myDropdown">
        <%= link_to 'Create Club', new_club_path, method: :get %>
        <%= link_to 'Create Category', new_category_path, method: :get %>
        <%= link_to 'My Ratings', my_ratings_path, method: :get %>
        <%= link_to "Settings", edit_user_registration_path, method: :get %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      </div>
    </div>
  <% else %>
    <div class="nav-items">
      <li><%= link_to 'About', about_path, method: :get %></li>
      <li><%= link_to 'Club Categories', categories_path, method: :get %></li>      
      <li class="mobile-menu"><%= link_to 'Login', new_user_session_path, method: :get %></li>
      <li class="mobile-menu"><%= link_to 'Sign Up', new_user_registration_path, method: :get %></li>  
    </div>
    <div class="search-icon"><span class="fa fa-search"></span></div>
    <div class="cancel-icon"><span class="fa fa-times"></span></div>
    <%= form_tag(clubs_path, method: :get) do %>
      <%= text_field_tag(:search, params[:search], placeholder: "Search for Club", class: "search-data") %>
      <button type="submit" class="fa fa-search" style="color: black"></button>
    <% end %>
    <div class="nav-items-right">
      <li><%= link_to 'Login', new_user_session_path, method: :get %></li>
      <li><%= link_to 'Sign Up', new_user_registration_path, method: :get %></li>        
    </div>  
  <% end %>
</nav>
  
</body>
</html>